apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-web-ingress
spec:
  rules:
  - host: simple-web.yourdomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: simple-web-service
          servicePort: 80
